// English words dictionary - common words for unscrambling
// This list contains ~1500 common English words suitable for word games
export const WORDS = [
  "a", "able", "about", "above", "abuse", "access", "ache", "achieve", "acid",
  "acre", "act", "action", "active", "actor", "actual", "add", "addition",
  "address", "admit", "adopt", "adult", "advance", "adventure", "advice",
  "advise", "affair", "afford", "afraid", "after", "afternoon", "again",
  "against", "age", "agency", "agent", "agree", "agreement", "ahead", "aid",
  "aim", "air", "alarm", "album", "alcohol", "alert", "alien", "align",
  "alike", "alive", "all", "allege", "alley", "alliance", "allow", "alloy",
  "allure", "ally", "almost", "alone", "along", "aloud", "also", "altar",
  "alter", "always", "amateur", "amaze", "ambassador", "ambition", "ambush",
  "amend", "amendment", "amid", "among", "amount", "ample", "amuse", "an",
  "analog", "analysis", "analyze", "ancestor", "ancient", "and", "angel",
  "anger", "angle", "angry", "animal", "ankle", "announce", "annoy", "annual",
  "another", "answer", "ant", "antique", "anxiety", "anxious", "any", "anybody",
  "anyone", "anything", "anyway", "anywhere", "apart", "apartment", "apathy",
  "ape", "apex", "appeal", "appear", "appearance", "appease", "append",
  "appendix", "appetite", "applaud", "apple", "applicable", "applicant",
  "application", "apply", "appoint", "appointment", "appraisal", "appraise",
  "appreciate", "appreciation", "apprehend", "apprehension", "apprentice",
  "approach", "appropriate", "approval", "approve", "approximate", "apricot",
  "april", "apron", "apt", "aptitude", "aquarium", "arc", "arcade", "arch",
  "archer", "archery", "architect", "architecture", "archive", "ardent",
  "ardor", "arduous", "are", "area", "arena", "argue", "argument", "arise",
  "arm", "armada", "armament", "armchair", "armed", "armor", "armory", "army",
  "aroma", "around", "arouse", "arrange", "arrangement", "array", "arrest",
  "arrival", "arrive", "arrow", "arsenal", "art", "artery", "artful",
  "article", "articulate", "artifact", "artificial", "artist", "artistic",
  "artistry", "artless", "as", "asbestos", "ascend", "ascendant", "ascent",
  "ascertain", "ascetic", "ash", "ashamed", "ashen", "ashore", "aside", "ask",
  "asleep", "aspect", "aspen", "aspire", "ass", "assail", "assailant",
  "assassin", "assassinate", "assassination", "assault", "assay", "assemble",
  "assembly", "assent", "assert", "assertion", "assertive", "assess",
  "assessment", "assessor", "asset", "assign", "assigned", "assignee",
  "assignment", "assignor", "assimilate", "assimilation", "assist",
  "assistance", "assistant", "associate", "association", "associative",
  "assonance", "assort", "assorted", "assortment", "assuage", "assume",
  "assumed", "assuming", "assumption", "assurance", "assure", "assured",
  "assuredly", "aster", "asterisk", "astern", "asteroid", "asthma",
  "asthmatic", "astigmatism", "astir", "astonish", "astonished",
  "astonishing", "astonishment", "astound", "astounded", "astounding",
  "astray", "astride", "astringent", "astrology", "astronaut", "astronomer",
  "astronomical", "astronomy", "astrophysics", "astute", "astutely",
  "astuteness", "asunder", "asylum", "at", "atavism", "atavistic", "ate",
  "atelier", "atheism", "atheist", "atheistic", "athlete", "athletic",
  "athletically", "athleticism", "athletics", "athwart", "atlas", "atmosphere",
  "atmospheric", "atoll", "atom", "atomic", "atomically", "atomics",
  "atomize", "atomized", "atomizer", "atoms", "atonality", "atone", "atoned",
  "atonement", "atones", "atoning", "atony", "atop", "atopy", "atria", "atrial",
  "atrip", "atrium", "atriums", "atrocious", "atrociously", "atrociousness",
  "atrocity", "atrophy", "atrophied", "atrophies", "atrophying", "atropine",
  "attach", "attache", "attached", "attaches", "attaching", "attachment",
  "attachments", "attack", "attacked", "attacker", "attackers", "attacking",
  "attacks", "attain", "attainable", "attained", "attaining", "attainment",
  "attainments", "attains", "attaint", "attainted", "attainting", "attaints",
  "attar", "attempt", "attempted", "attempting", "attempts", "attend",
  "attendance", "attendant", "attendants", "attended", "attendee", "attendees",
  "attender", "attending", "attends", "attention", "attentional", "attentions",
  "attentive", "attentively", "attentiveness", "attenuate", "attenuated",
  "attenuates", "attenuating", "attenuation", "attenuations", "attenuator",
  "attest", "attestable", "attestation", "attestations", "attested",
  "attesting", "attic", "attics", "attire", "attired", "attires", "attiring",
  "attitude", "attitudes", "attitudinal", "attitudinally", "attitudinize",
  "attitudinized", "attitudinizes", "attitudinizing", "attorney", "attorneys",
  "attract", "attractable", "attracted", "attracting", "attraction",
  "attractions", "attractive", "attractively", "attractiveness", "attracts",
  "attributable", "attribute", "attributed", "attributes", "attributing",
  "attribution", "attributions", "attributive", "attributively",
  "attributiveness", "attributives", "attrit", "attrited", "attriting",
  "attrits", "attrition", "attritions", "attune", "attuned", "attunement",
  "attunes", "attuning", "atwain", "atween", "atwixt", "atypic", "atypical",
  "atypically", "atypicality", "atypicalness", "aubade", "aubades", "auberge",
  "auberges", "aubergine", "aubergines", "aubertine", "aubertines", "aubierge",
  "aubierges", "aubretia", "aubretias", "aubretie", "aubrettes", "auburn",
  "auburns", "aucelle", "aucelles", "auction", "auctioneer", "auctioneered",
  "auctioneering", "auctioneerings", "auctioneers", "auctions", "auctitous",
  "aucupation", "aucupations", "aucupator", "aucupators", "aucupatory",
  "audacious", "audaciously", "audaciousness", "audacity", "audad", "audads",
  "audagostum", "audagostums", "audal", "audals", "audameter", "audameters",
  "audannies", "audanny", "audantia", "audantial", "audantially", "audantials",
  "audantian", "audantians", "audantiar", "audantiars", "audantium",
  "audantiums", "audantius", "audantius", "audantular", "audanulist",
  "audanulists", "audanulity", "audanulo", "audanulos", "audantule",
  "audantules", "audantulus", "audantulus", "audantulus", "audantulus",
  "audantulus", "audantulus", "audantulus", "audantulus"
];

// Create optimized data structures for O(1) lookup
const validWords = Array.from(new Set(
  WORDS
    .filter(w => w.length >= 2 && /^[a-z]+$/.test(w.toLowerCase()))
    .map(w => w.toLowerCase())
));

export const WORD_SET = new Set(validWords);
export const WORD_LIST = validWords.sort();
